-- Base global de futbolistas y migración reversible desde jugadores_rivales.
-- Ejecutar el archivo completo en Supabase SQL Editor. No elimina ninguna tabla ni columna legacy.
begin;

create table if not exists public.players_database (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  photo_url text,
  dob date,
  age text,
  height text,
  foot text,
  scouting_summary varchar(500),
  card_alert boolean not null default false,
  sent_off_alert boolean not null default false,
  suspended_alert boolean not null default false,
  injured_alert boolean not null default false,
  external_source text,
  external_player_id text,
  field_sources jsonb not null default '{}'::jsonb,
  legacy_origin_id uuid unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.players_database add column if not exists age text;

create unique index if not exists players_database_external_identity_uidx
on public.players_database (lower(external_source), external_player_id)
where external_source is not null and external_player_id is not null;

create index if not exists players_database_name_idx
on public.players_database (lower(name));

create table if not exists public.player_team_memberships (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players_database(id) on delete cascade,
  team_id uuid not null references public.equipos_rivales(id) on delete cascade,
  season text,
  start_date date,
  end_date date,
  is_current boolean not null default true,
  number text,
  captain boolean not null default false,
  is_key boolean not null default false,
  observed boolean not null default false,
  squad_role text,
  tactical_role text,
  tactical_slot integer,
  tactical_reserve_slot integer,
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint player_team_memberships_role_check check (tactical_role is null or tactical_role in ('Titular', 'Reserva')),
  constraint player_team_memberships_slot_check check (tactical_slot is null or tactical_slot between 0 and 10),
  constraint player_team_memberships_reserve_slot_check check (tactical_reserve_slot is null or tactical_reserve_slot between 0 and 1),
  constraint player_team_memberships_placement_check check (
    (tactical_role is null and tactical_slot is null and tactical_reserve_slot is null)
    or (tactical_role = 'Titular' and tactical_slot is not null and tactical_reserve_slot is null)
    or (tactical_role = 'Reserva' and tactical_slot is not null and tactical_reserve_slot is not null)
  )
);

create unique index if not exists player_team_memberships_current_stage_uidx
on public.player_team_memberships (player_id, team_id)
where is_current;

create index if not exists player_team_memberships_team_current_idx
on public.player_team_memberships (team_id, is_current);

create unique index if not exists player_team_memberships_starter_slot_uidx
on public.player_team_memberships (team_id, tactical_slot)
where is_current and tactical_role = 'Titular' and tactical_slot is not null;

create unique index if not exists player_team_memberships_reserve_slot_uidx
on public.player_team_memberships (team_id, tactical_slot, tactical_reserve_slot)
where is_current and tactical_role = 'Reserva' and tactical_slot is not null and tactical_reserve_slot is not null;

create table if not exists public.player_positions (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players_database(id) on delete cascade,
  position_type text not null check (position_type in ('natural', 'specific')),
  position_key text not null,
  is_primary boolean not null default false,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint player_positions_key_check check (
    (position_type = 'natural' and position_key in ('goalkeeper', 'defender', 'midfielder', 'forward'))
    or (position_type = 'specific' and position_key in (
      'goalkeeper', 'sweeper_keeper', 'right_back', 'left_back', 'right_wing_back', 'left_wing_back',
      'centre_back', 'right_centre_back', 'left_centre_back', 'libero', 'holding_midfield',
      'defensive_midfield', 'central_midfield', 'right_central_midfield', 'left_central_midfield',
      'attacking_midfield', 'right_midfield', 'left_midfield', 'right_winger', 'left_winger',
      'second_striker', 'centre_forward', 'mobile_forward', 'target_forward'
    ))
  ),
  unique (player_id, position_type, position_key)
);

create unique index if not exists player_positions_one_primary_per_type_uidx
on public.player_positions (player_id, position_type)
where is_primary;

create index if not exists player_positions_key_idx
on public.player_positions (position_type, position_key, player_id);

create table if not exists public.player_sources (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players_database(id) on delete cascade,
  url text not null,
  source_name text not null default 'Otro',
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  unique (player_id, url)
);

create unique index if not exists player_sources_one_primary_uidx
on public.player_sources (player_id)
where is_primary;

create table if not exists public.player_scouting_traits (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players_database(id) on delete cascade,
  category text not null check (category in ('strength', 'vulnerability', 'trend')),
  label text not null,
  position_family text,
  created_at timestamptz not null default now(),
  unique (player_id, category, label)
);

create table if not exists public.legacy_rival_player_migration (
  legacy_player_id uuid primary key references public.jugadores_rivales(id) on delete cascade,
  global_player_id uuid not null references public.players_database(id) on delete cascade,
  membership_id uuid references public.player_team_memberships(id) on delete set null,
  match_basis text not null default 'legacy_row',
  review_status text not null default 'pending' check (review_status in ('pending', 'confirmed', 'possible_duplicate')),
  created_at timestamptz not null default now()
);

alter table public.jugadores_rivales
  add column if not exists global_player_id uuid references public.players_database(id) on delete set null,
  add column if not exists membership_id uuid references public.player_team_memberships(id) on delete set null;

alter table public.equipo_rival_alineacion
  add column if not exists global_player_id uuid references public.players_database(id) on delete set null,
  add column if not exists membership_id uuid references public.player_team_memberships(id) on delete set null;

alter table public.equipo_rival_banquillo
  add column if not exists global_player_id uuid references public.players_database(id) on delete set null,
  add column if not exists membership_id uuid references public.player_team_memberships(id) on delete set null;

alter table public.partido_alineacion_slots
  add column if not exists global_player_id uuid references public.players_database(id) on delete set null,
  add column if not exists membership_id uuid references public.player_team_memberships(id) on delete set null;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists players_database_touch_updated_at on public.players_database;
create trigger players_database_touch_updated_at before update on public.players_database
for each row execute function public.touch_updated_at();

drop trigger if exists player_team_memberships_touch_updated_at on public.player_team_memberships;
create trigger player_team_memberships_touch_updated_at before update on public.player_team_memberships
for each row execute function public.touch_updated_at();

drop trigger if exists player_positions_touch_updated_at on public.player_positions;
create trigger player_positions_touch_updated_at before update on public.player_positions
for each row execute function public.touch_updated_at();

-- Migración conservadora: un perfil por fila legacy. Nunca une automáticamente solo por nombre.
insert into public.players_database (
  name, photo_url, dob, age, height, foot, scouting_summary,
  card_alert, sent_off_alert, suspended_alert, injured_alert,
  external_source, external_player_id, field_sources, legacy_origin_id
)
select distinct on (candidate.identity_key)
  candidate.name, candidate.image, candidate.dob, candidate.age, candidate.height, candidate.foot, left(candidate.notes, 500),
  coalesce(candidate.card_alert, candidate.yellow_risk, false), coalesce(candidate.sent_off_alert, false),
  coalesce(candidate.suspended_alert, candidate.suspended, false), coalesce(candidate.injured_alert, candidate.injured, false),
  nullif(trim(candidate.external_source), ''), nullif(trim(candidate.external_player_id), ''), coalesce(candidate.field_sources, '{}'::jsonb), candidate.id
from (
  select jr.*,
    case when nullif(trim(jr.external_source), '') is not null and nullif(trim(jr.external_player_id), '') is not null
      then 'external:' || lower(trim(jr.external_source)) || ':' || trim(jr.external_player_id)
      else 'legacy:' || jr.id::text
    end as identity_key
  from public.jugadores_rivales jr
) candidate
where not exists (
  select 1 from public.players_database gp
  where gp.legacy_origin_id = candidate.id
     or (
       nullif(trim(candidate.external_source), '') is not null and nullif(trim(candidate.external_player_id), '') is not null
       and lower(gp.external_source) = lower(trim(candidate.external_source))
       and gp.external_player_id = trim(candidate.external_player_id)
     )
)
order by candidate.identity_key, candidate.id;

insert into public.legacy_rival_player_migration (legacy_player_id, global_player_id, match_basis)
select jr.id, matched.id,
  case when matched.legacy_origin_id = jr.id then 'legacy_row' else 'external_id' end
from public.jugadores_rivales jr
join lateral (
  select gp.id, gp.legacy_origin_id
  from public.players_database gp
  where gp.legacy_origin_id = jr.id
     or (
       nullif(trim(jr.external_source), '') is not null and nullif(trim(jr.external_player_id), '') is not null
       and lower(gp.external_source) = lower(trim(jr.external_source))
       and gp.external_player_id = trim(jr.external_player_id)
     )
  order by (gp.legacy_origin_id = jr.id) desc
  limit 1
) matched on true
on conflict (legacy_player_id) do update
set global_player_id = excluded.global_player_id, match_basis = excluded.match_basis;

insert into public.player_team_memberships (
  player_id, team_id, is_current, number, captain, is_key, observed, squad_role,
  tactical_role, tactical_slot, tactical_reserve_slot, source_url
)
select distinct on (migration.global_player_id, jr.equipo_rival_id, coalesce(jr.active_in_squad, true))
  migration.global_player_id, jr.equipo_rival_id, coalesce(jr.active_in_squad, true), jr.number,
  coalesce(jr.captain, false), coalesce(jr.is_key, false), coalesce(jr.observed, false), jr.role,
  jr.tactical_role, jr.tactical_slot, jr.tactical_reserve_slot, jr.source_profile_url
from public.jugadores_rivales jr
join public.legacy_rival_player_migration migration on migration.legacy_player_id = jr.id
where not exists (
  select 1 from public.player_team_memberships membership
  where membership.player_id = migration.global_player_id and membership.team_id = jr.equipo_rival_id and membership.is_current = coalesce(jr.active_in_squad, true)
)
order by migration.global_player_id, jr.equipo_rival_id, coalesce(jr.active_in_squad, true) desc, jr.id;

insert into public.legacy_rival_player_migration (legacy_player_id, global_player_id, membership_id)
select jr.id, migration.global_player_id, membership.id
from public.jugadores_rivales jr
join public.legacy_rival_player_migration migration on migration.legacy_player_id = jr.id
left join lateral (
  select item.id from public.player_team_memberships item
  where item.player_id = migration.global_player_id and item.team_id = jr.equipo_rival_id
  order by item.is_current desc, item.created_at desc limit 1
) membership on true
on conflict (legacy_player_id) do update
set global_player_id = excluded.global_player_id, membership_id = excluded.membership_id;

update public.jugadores_rivales jr
set global_player_id = migration.global_player_id,
    membership_id = migration.membership_id
from public.legacy_rival_player_migration migration
where migration.legacy_player_id = jr.id
  and (jr.global_player_id is distinct from migration.global_player_id or jr.membership_id is distinct from migration.membership_id);

-- Posición natural legacy -> clave estable. No se inventan secundarias.
insert into public.player_positions (player_id, position_type, position_key, is_primary, source)
select migration.global_player_id, 'natural',
  case
    when lower(coalesce(jr.position, '')) in ('portero', 'goalkeeper') then 'goalkeeper'
    when lower(coalesce(jr.position, '')) in ('defensa', 'defender') then 'defender'
    when lower(coalesce(jr.position, '')) in ('mediocentro', 'centrocampista', 'midfielder') then 'midfielder'
    when lower(coalesce(jr.position, '')) in ('delantero', 'atacante', 'forward') then 'forward'
    when lower(coalesce(jr.specific_position, '')) like any (array['%lateral%', '%carrilero%', '%central%', '%líbero%', '%libero%']) then 'defender'
    when lower(coalesce(jr.specific_position, '')) like any (array['%pivote%', '%medio%', '%interior%', '%mediapunta%']) then 'midfielder'
    when lower(coalesce(jr.specific_position, '')) like any (array['%extremo%', '%delantero%', '%punta%']) then 'forward'
    else null
  end,
  false,
  coalesce(jr.field_sources -> 'position' ->> 'source', 'legacy')
from public.jugadores_rivales jr
join public.legacy_rival_player_migration migration on migration.legacy_player_id = jr.id
where lower(coalesce(jr.position, '')) in ('portero', 'goalkeeper', 'defensa', 'defender', 'mediocentro', 'centrocampista', 'midfielder', 'delantero', 'atacante', 'forward')
   or lower(coalesce(jr.specific_position, '')) like any (array['%lateral%', '%carrilero%', '%central%', '%líbero%', '%libero%', '%pivote%', '%medio%', '%interior%', '%mediapunta%', '%extremo%', '%delantero%', '%punta%'])
on conflict (player_id, position_type, position_key) do nothing;

delete from public.player_positions where position_key is null;

update public.player_positions candidate
set is_primary = true
where candidate.position_type = 'natural'
  and candidate.id = (
    select first_position.id
    from public.player_positions first_position
    where first_position.player_id = candidate.player_id and first_position.position_type = 'natural'
    order by first_position.id
    limit 1
  )
  and not exists (
    select 1 from public.player_positions current_primary
    where current_primary.player_id = candidate.player_id
      and current_primary.position_type = 'natural'
      and current_primary.is_primary
  );

insert into public.player_positions (player_id, position_type, position_key, is_primary, source)
select migration.global_player_id, 'specific',
  case
    when lower(coalesce(jr.specific_position, '')) in ('portero', 'goalkeeper') then 'goalkeeper'
    when lower(coalesce(jr.specific_position, '')) in ('portero-líbero', 'portero-libero') then 'sweeper_keeper'
    when lower(coalesce(jr.specific_position, '')) = 'lateral derecho' then 'right_back'
    when lower(coalesce(jr.specific_position, '')) = 'lateral izquierdo' then 'left_back'
    when lower(coalesce(jr.specific_position, '')) = 'carrilero derecho' then 'right_wing_back'
    when lower(coalesce(jr.specific_position, '')) = 'carrilero izquierdo' then 'left_wing_back'
    when lower(coalesce(jr.specific_position, '')) in ('defensa central', 'central') then 'centre_back'
    when lower(coalesce(jr.specific_position, '')) = 'central derecho' then 'right_centre_back'
    when lower(coalesce(jr.specific_position, '')) = 'central izquierdo' then 'left_centre_back'
    when lower(coalesce(jr.specific_position, '')) in ('líbero', 'libero') then 'libero'
    when lower(coalesce(jr.specific_position, '')) = 'pivote' then 'holding_midfield'
    when lower(coalesce(jr.specific_position, '')) in ('mediocentro defensivo', 'medio defensivo') then 'defensive_midfield'
    when lower(coalesce(jr.specific_position, '')) in ('mediocentro', 'centrocampista') then 'central_midfield'
    when lower(coalesce(jr.specific_position, '')) = 'interior derecho' then 'right_central_midfield'
    when lower(coalesce(jr.specific_position, '')) = 'interior izquierdo' then 'left_central_midfield'
    when lower(coalesce(jr.specific_position, '')) in ('mediapunta', 'mediocentro ofensivo') then 'attacking_midfield'
    when lower(coalesce(jr.specific_position, '')) = 'extremo derecho' then 'right_winger'
    when lower(coalesce(jr.specific_position, '')) = 'extremo izquierdo' then 'left_winger'
    when lower(coalesce(jr.specific_position, '')) = 'segundo delantero' then 'second_striker'
    when lower(coalesce(jr.specific_position, '')) in ('delantero centro', 'delantero', 'punta') then 'centre_forward'
    else null
  end,
  false,
  coalesce(jr.field_sources -> 'specificPosition' ->> 'source', 'legacy')
from public.jugadores_rivales jr
join public.legacy_rival_player_migration migration on migration.legacy_player_id = jr.id
where lower(coalesce(jr.specific_position, '')) in (
  'portero', 'goalkeeper', 'portero-líbero', 'portero-libero', 'lateral derecho', 'lateral izquierdo',
  'carrilero derecho', 'carrilero izquierdo', 'defensa central', 'central', 'central derecho', 'central izquierdo',
  'líbero', 'libero', 'pivote', 'mediocentro defensivo', 'medio defensivo', 'mediocentro', 'centrocampista',
  'interior derecho', 'interior izquierdo', 'mediapunta', 'mediocentro ofensivo', 'extremo derecho',
  'extremo izquierdo', 'segundo delantero', 'delantero centro', 'delantero', 'punta'
)
on conflict (player_id, position_type, position_key) do nothing;

delete from public.player_positions where position_key is null;

update public.player_positions candidate
set is_primary = true
where candidate.position_type = 'specific'
  and candidate.id = (
    select first_position.id
    from public.player_positions first_position
    where first_position.player_id = candidate.player_id and first_position.position_type = 'specific'
    order by first_position.id
    limit 1
  )
  and not exists (
    select 1 from public.player_positions current_primary
    where current_primary.player_id = candidate.player_id
      and current_primary.position_type = 'specific'
      and current_primary.is_primary
  );

insert into public.player_sources (player_id, url, source_name, is_primary)
select migration.global_player_id, jr.source_profile_url,
  case when lower(coalesce(jr.external_source, '')) = 'transfermarkt' then 'Transfermarkt' else coalesce(nullif(jr.external_source, ''), 'Fuente legacy') end,
  false
from public.jugadores_rivales jr
join public.legacy_rival_player_migration migration on migration.legacy_player_id = jr.id
where nullif(trim(jr.source_profile_url), '') is not null
on conflict (player_id, url) do nothing;

update public.player_sources source
set is_primary = true
where source.id = (
  select candidate.id from public.player_sources candidate
  where candidate.player_id = source.player_id
  order by candidate.created_at, candidate.id limit 1
)
and not exists (
  select 1 from public.player_sources current_primary
  where current_primary.player_id = source.player_id and current_primary.is_primary
);

-- Auditoría: coincidencias que requieren revisión humana antes de unir perfiles.
create or replace view public.player_possible_duplicates
with (security_invoker = true) as
select
  left_player.id as player_id,
  right_player.id as possible_duplicate_id,
  left_player.name,
  case
    when left_player.external_source is not null and left_player.external_source = right_player.external_source and left_player.external_player_id = right_player.external_player_id then 'external_id'
    when left_player.dob is not null and left_player.dob = right_player.dob then 'name_dob'
    else 'name_only'
  end as match_basis
from public.players_database left_player
join public.players_database right_player on left_player.id < right_player.id
  and regexp_replace(lower(trim(left_player.name)), '[^a-z0-9áéíóúüñ]+', '', 'g') = regexp_replace(lower(trim(right_player.name)), '[^a-z0-9áéíóúüñ]+', '', 'g')
where (
  left_player.external_source is not null and left_player.external_source = right_player.external_source and left_player.external_player_id = right_player.external_player_id
) or left_player.dob = right_player.dob or (left_player.dob is null and right_player.dob is null);

-- Auditoría operativa por rival. Permite comparar cobertura global y filas legacy pendientes.
create or replace view public.global_player_coverage_by_team
with (security_invoker = true) as
select
  team.id as team_id,
  team.name as team_name,
  (
    select count(distinct membership.player_id)
    from public.player_team_memberships membership
    where membership.team_id = team.id and membership.is_current
  ) as global_players_linked,
  (
    select count(*)
    from public.jugadores_rivales legacy
    where legacy.equipo_rival_id = team.id
      and coalesce(legacy.active_in_squad, true)
      and (
        legacy.global_player_id is null
        or not exists (
          select 1
          from public.player_team_memberships membership
          where membership.player_id = legacy.global_player_id
            and membership.team_id = team.id
            and membership.is_current
        )
      )
  ) as legacy_players_pending
from public.equipos_rivales team;

alter table public.players_database enable row level security;
alter table public.player_team_memberships enable row level security;
alter table public.player_positions enable row level security;
alter table public.player_sources enable row level security;
alter table public.player_scouting_traits enable row level security;
alter table public.legacy_rival_player_migration enable row level security;

do $$
declare table_name text;
begin
  foreach table_name in array array['players_database', 'player_team_memberships', 'player_positions', 'player_sources', 'player_scouting_traits', 'legacy_rival_player_migration']
  loop
    execute format('drop policy if exists "Authenticated staff can read %s" on public.%I', table_name, table_name);
    execute format('create policy "Authenticated staff can read %s" on public.%I for select to authenticated using (true)', table_name, table_name);
    execute format('drop policy if exists "Authenticated staff can insert %s" on public.%I', table_name, table_name);
    execute format('create policy "Authenticated staff can insert %s" on public.%I for insert to authenticated with check (true)', table_name, table_name);
    execute format('drop policy if exists "Authenticated staff can update %s" on public.%I', table_name, table_name);
    execute format('create policy "Authenticated staff can update %s" on public.%I for update to authenticated using (true) with check (true)', table_name, table_name);
    execute format('drop policy if exists "Authenticated staff can delete %s" on public.%I', table_name, table_name);
    execute format('create policy "Authenticated staff can delete %s" on public.%I for delete to authenticated using (true)', table_name, table_name);
  end loop;
end $$;

comment on table public.players_database is 'Fuente única del perfil estable del futbolista, independiente de su club.';
comment on table public.player_team_memberships is 'Etapas históricas del futbolista en equipos rivales; una vuelta al mismo club crea una etapa nueva.';
comment on table public.player_positions is 'Posiciones naturales y específicas múltiples, con principal explícita y origen por posición.';
comment on table public.player_sources is 'Referencias acumulativas del jugador; añadir una fuente nunca sustituye las anteriores.';
comment on table public.player_scouting_traits is 'Fortalezas, vulnerabilidades y tendencias observables del futbolista.';

create or replace function public.save_global_player_profile(
  p_player jsonb,
  p_positions jsonb default '[]'::jsonb,
  p_sources jsonb default '[]'::jsonb,
  p_traits jsonb default '[]'::jsonb,
  p_membership jsonb default null
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  global_id uuid;
  membership_id uuid;
begin
  global_id := nullif(p_player ->> 'id', '')::uuid;
  if global_id is null then
    insert into public.players_database (
      name, photo_url, dob, age, height, foot, scouting_summary,
      card_alert, sent_off_alert, suspended_alert, injured_alert,
      external_source, external_player_id, field_sources
    ) values (
      trim(p_player ->> 'name'), nullif(p_player ->> 'photoUrl', ''), nullif(p_player ->> 'dob', '')::date, nullif(p_player ->> 'age', ''),
      nullif(p_player ->> 'height', ''), nullif(p_player ->> 'foot', ''), left(nullif(p_player ->> 'scoutingSummary', ''), 500),
      coalesce((p_player ->> 'cardAlert')::boolean, false), coalesce((p_player ->> 'sentOffAlert')::boolean, false),
      coalesce((p_player ->> 'suspendedAlert')::boolean, false), coalesce((p_player ->> 'injuredAlert')::boolean, false),
      nullif(p_player ->> 'externalSource', ''), nullif(p_player ->> 'externalPlayerId', ''), coalesce(p_player -> 'fieldSources', '{}'::jsonb)
    ) returning id into global_id;
  else
    update public.players_database set
      name = trim(p_player ->> 'name'),
      photo_url = nullif(p_player ->> 'photoUrl', ''),
      dob = nullif(p_player ->> 'dob', '')::date,
      age = nullif(p_player ->> 'age', ''),
      height = nullif(p_player ->> 'height', ''),
      foot = nullif(p_player ->> 'foot', ''),
      scouting_summary = left(nullif(p_player ->> 'scoutingSummary', ''), 500),
      card_alert = coalesce((p_player ->> 'cardAlert')::boolean, false),
      sent_off_alert = coalesce((p_player ->> 'sentOffAlert')::boolean, false),
      suspended_alert = coalesce((p_player ->> 'suspendedAlert')::boolean, false),
      injured_alert = coalesce((p_player ->> 'injuredAlert')::boolean, false),
      external_source = nullif(p_player ->> 'externalSource', ''),
      external_player_id = nullif(p_player ->> 'externalPlayerId', ''),
      field_sources = coalesce(p_player -> 'fieldSources', field_sources)
    where id = global_id;
    if not found then raise exception 'Jugador global no encontrado'; end if;
  end if;

  delete from public.player_positions where player_id = global_id;
  insert into public.player_positions (player_id, position_type, position_key, is_primary, source)
  select global_id, item.position_type, item.position_key, item.is_primary, coalesce(nullif(item.source, ''), 'manual')
  from jsonb_to_recordset(coalesce(p_positions, '[]'::jsonb))
    as item(position_type text, position_key text, is_primary boolean, source text);

  delete from public.player_sources where player_id = global_id;
  insert into public.player_sources (player_id, url, source_name, is_primary)
  select global_id, item.url, coalesce(nullif(item.source_name, ''), 'Otro'), item.is_primary
  from jsonb_to_recordset(coalesce(p_sources, '[]'::jsonb))
    as item(url text, source_name text, is_primary boolean)
  where nullif(trim(item.url), '') is not null;

  delete from public.player_scouting_traits where player_id = global_id;
  insert into public.player_scouting_traits (player_id, category, label, position_family)
  select global_id, item.category, trim(item.label), nullif(item.position_family, '')
  from jsonb_to_recordset(coalesce(p_traits, '[]'::jsonb))
    as item(category text, label text, position_family text)
  where nullif(trim(item.label), '') is not null;

  if p_membership is not null and nullif(p_membership ->> 'teamId', '') is not null then
    membership_id := nullif(p_membership ->> 'id', '')::uuid;
    if membership_id is null then
      select id into membership_id from public.player_team_memberships
      where player_id = global_id and team_id = (p_membership ->> 'teamId')::uuid and is_current
      order by created_at desc limit 1;
    end if;
    if membership_id is null then
      if coalesce(nullif(p_membership ->> 'mode', ''), 'replace') = 'replace' then
        update public.player_team_memberships
        set is_current = false, end_date = coalesce(end_date, current_date)
        where player_id = global_id and is_current and team_id <> (p_membership ->> 'teamId')::uuid;
      end if;
      insert into public.player_team_memberships (
        player_id, team_id, season, start_date, is_current, number, captain, is_key, observed, source_url
      ) values (
        global_id, (p_membership ->> 'teamId')::uuid, nullif(p_membership ->> 'season', ''),
        nullif(p_membership ->> 'startDate', '')::date, true, nullif(p_membership ->> 'number', ''),
        coalesce((p_membership ->> 'captain')::boolean, false), coalesce((p_membership ->> 'isKey')::boolean, false),
        coalesce((p_membership ->> 'observed')::boolean, false), nullif(p_membership ->> 'sourceUrl', '')
      );
    else
      update public.player_team_memberships set
        season = nullif(p_membership ->> 'season', ''), number = nullif(p_membership ->> 'number', ''),
        captain = coalesce((p_membership ->> 'captain')::boolean, false),
        is_key = coalesce((p_membership ->> 'isKey')::boolean, false),
        observed = coalesce((p_membership ->> 'observed')::boolean, false)
      where id = membership_id and player_id = global_id;
    end if;
  end if;
  return global_id;
end $$;

create or replace function public.assign_global_player_to_team(
  p_player_id uuid,
  p_team_id uuid,
  p_mode text default 'replace',
  p_season text default null,
  p_start_date date default current_date
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare membership_id uuid;
begin
  select id into membership_id from public.player_team_memberships
  where player_id = p_player_id and team_id = p_team_id and is_current
  order by created_at desc limit 1;
  if membership_id is not null then return membership_id; end if;
  if p_mode = 'replace' then
    update public.player_team_memberships
    set is_current = false, end_date = coalesce(end_date, p_start_date)
    where player_id = p_player_id and is_current;
  elsif p_mode <> 'keep_both' then
    raise exception 'Modo de afiliación no válido: %', p_mode;
  end if;
  insert into public.player_team_memberships (player_id, team_id, season, start_date, is_current)
  values (p_player_id, p_team_id, p_season, p_start_date, true)
  returning id into membership_id;
  return membership_id;
end $$;

commit;

-- REVERSIÓN (solo si se decide volver atrás tras validar una copia de seguridad):
-- begin;
-- alter table public.partido_alineacion_slots drop column if exists membership_id, drop column if exists global_player_id;
-- alter table public.equipo_rival_banquillo drop column if exists membership_id, drop column if exists global_player_id;
-- alter table public.equipo_rival_alineacion drop column if exists membership_id, drop column if exists global_player_id;
-- alter table public.jugadores_rivales drop column if exists membership_id, drop column if exists global_player_id;
-- drop view if exists public.player_possible_duplicates;
-- drop view if exists public.global_player_coverage_by_team;
-- drop table if exists public.legacy_rival_player_migration, public.player_scouting_traits, public.player_sources,
--   public.player_positions, public.player_team_memberships, public.players_database;
-- commit;
