import assert from 'node:assert/strict';
import { buildTrainingTaskCardPresentation, formatTrainingTaskCardStages } from './trainingTaskCardPresentation.js';

assert.equal(formatTrainingTaskCardStages(['juvenil', 'senior']), 'Juvenil · Sénior');
assert.equal(formatTrainingTaskCardStages(['infantil', 'cadete', 'juvenil', 'senior']), 'Infantil · Cadete · +2');
const card = buildTrainingTaskCardPresentation({ author_user_id: 'u1', taskType: 'rondos', playersSpec: '6v6+2', durationMinutes: 18, spaceWidthM: 40, spaceLengthM: 30, objective: 'Conservar', description: 'Fallback', variants: 'Una variante libre', ratingAverage: 4.25, ratingCount: 4, feedbackCount: 5 }, 'u1');
assert.equal(card.type.label, 'Rondos');
assert.equal(card.players, '6v6+2');
assert.equal(card.duration, "18'");
assert.match(card.space, /40.*30/);
assert.equal(card.summary, 'Conservar');
assert.equal(card.variants, 'Con variantes');
assert.equal(card.rating, '4,3 (4)');
assert.equal(card.feedback, '5 registros POST');
assert.equal(card.ownership, 'Mía');
assert.equal(buildTrainingTaskCardPresentation({ description: 'Descripción', taskType: 'warm_up' }, 'u1').summary, 'Descripción');
assert.equal(buildTrainingTaskCardPresentation({ playersSpec: '8v8+2', playersMin: 5, playersMax: 30 }, 'u1').players, '8v8+2', 'players_spec prevalece sobre min/max');
assert.equal(buildTrainingTaskCardPresentation({ playersSpec: '', playersMin: 10, playersMax: 14 }, 'u1').players, '10-14', 'sin players_spec usa el rango estructurado');
assert.equal(buildTrainingTaskCardPresentation({ playersSpec: '   ', playersMin: 12, playersMax: 12 }, 'u1').players, '12', 'players_spec vacío no bloquea el fallback');
console.log('training task card presentation tests passed');
