import assert from 'node:assert/strict';
import fs from 'node:fs';

const component = fs.readFileSync(new URL('../src/components/delegated/DelegatedStatsDashboard.jsx', import.meta.url), 'utf8');
const app = fs.readFileSync(new URL('../src/App.jsx', import.meta.url), 'utf8');

assert.match(component, /\['Resumen', 'Jugadores', 'Equipo', 'Evolución'\]/, 'expone las cuatro vistas solicitadas');
assert.match(component, /buildDelegatedStatsDataset/, 'todas las vistas parten del dataset central');
assert.match(component, /aggregateDelegatedSides|buildDelegatedTeamProfile/, 'la UI reutiliza los agregadores centrales');
assert.match(component, /buildDelegatedPlayerRows/, 'la tabla individual usa la capa estadística');
assert.match(component, /buildDelegatedTemporalDistribution/, 'Equipo usa la distribución temporal central');
assert.match(component, /buildDelegatedTemporalMatrix/, 'Equipo usa la matriz temporal central');
assert.match(component, /buildDelegatedHalfComparison/, 'Equipo compara primera y segunda parte');
assert.match(component, /buildDelegatedContextComparison/, 'Equipo compara contextos reales');
assert.match(component, /buildDelegatedEvolution/, 'Evolución usa la serie central');
assert.match(component, /"Total"[\s\S]*"Media\/partido"[\s\S]*"Por90"/, 'incluye Total, Media/partido y Por90');
assert.match(component, /useState\('average'\)/, 'Media/partido es la vista predeterminada de jugadores');
assert.match(component, /Goles \+ asistencias[\s\S]*short: 'G\+A'|goalContributions/, 'la producción individual incluye G, A y G+A');
assert.match(component, /Oficial · goles, asistencias y minutos[\s\S]*Registro delegado · acciones/, 'identifica discretamente las dos fuentes');
assert.match(component, /Más filtros[\s\S]*aria-label="Resultado"[\s\S]*aria-label="Jugador"[\s\S]*aria-label="Equipo"[\s\S]*aria-label="Evento"[\s\S]*aria-label="Tramo"[\s\S]*aria-label="Muestra"/, 'los filtros secundarios viven en Más filtros');
assert.match(component, /aria-label="Partido"[\s\S]*aria-label="Competición"[\s\S]*aria-label="Local o visitante"[\s\S]*Más filtros/, 'la cabecera conserva solo los tres filtros principales');
assert.match(component, /orderedMatchOptions[\s\S]*formatMatchOption[\s\S]*roundLabel/, 'el selector ordena cronológicamente y muestra jornada solo cuando existe');
assert.match(component, /min-w-0 w-full rounded-xl/, 'los selectores pueden usar todo el ancho sin truncado artificial');
assert.match(component, /<EvolutionLineChart/, 'Evolución utiliza un gráfico de línea');
assert.match(component, /evolution\.length === 1[\s\S]*Muestra actual: 1 partido/, 'un único partido usa una ficha compacta sin gráfico grande');
assert.match(component, /compact=\{evolution\.length < 5\}/, 'dos a cuatro partidos usan evolución compacta');
assert.match(component, /setPlayerMode\(matchId \? 'total' : 'average'\)/, 'un partido prioriza Total y Todos los partidos recupera Media/partido');
assert.match(component, /singleMatchMode \? \[\["total", "Total"\], \["per90", "Por90"\]\]/, 'el partido individual elimina la media redundante del selector');
assert.match(component, /singleMatchMode \? <SelectedMatchComparison/, 'Evolución sustituye el gráfico de un punto por partido vs muestra');
assert.match(component, /Estadísticas del partido[\s\S]*Partido seleccionado/, 'Equipo cambia a lectura específica del encuentro');
assert.match(component, /rows\.length >= 5[\s\S]*Media móvil 5/, 'la media móvil solo aparece desde cinco partidos');
assert.match(component, /lineSegments/, 'el gráfico no une huecos sin muestra como si existieran datos');
assert.match(component, /Media móvil 5|media móvil de 5/i, 'muestra la media móvil de cinco partidos');
assert.match(component, /Lecturas de los datos/, 'incluye lecturas estadísticas deterministas');
assert.match(component, /Local \/ Visitante[\s\S]*Victoria \/ Empate \/ Derrota[\s\S]*Liga \/ Otras/, 'expone comparaciones contextuales');
assert.match(component, /disabled=\{Boolean\(filters\.playerId\)\}/, 'evita combinar un jugador propio con el filtro rival');
assert.match(component, /buildDelegatedOfficialTeamScore[\s\S]*buildDelegatedOfficialGoalEvents/, 'goles de resumen, equipo y evolución usan la fuente oficial');
assert.match(component, /Sin datos suficientes del rival/, 'no representa ausencia rival como ceros confirmados');
assert.match(component, /hasUnprocessedValidatedMatch[\s\S]*sus eventos siguen pendientes/, 'explica el estado Validado heredado sin reviewed');
assert.match(component, /DELEGATED_PANEL_PLAYER_STAT_FIELDS[\s\S]*DELEGATED_PANEL_STAT_FIELDS/, 'la UI consume catálogos específicos del panel');
assert.match(component, /PANEL_EVENT_CATALOG = DELEGATED_EVENT_CATALOG\.filter[\s\S]*DELEGATED_PANEL_EXCLUDED_STAT_KEYS/, 'Más filtros reutiliza la exclusión central de métricas retiradas');
assert.doesNotMatch(component, /REG Regates|REC Recuperaciones|Más regates|Más recuperaciones|robos \+ recuperaciones/i, 'no quedan columnas, leyendas, rankings ni derivados visibles de las métricas retiradas');
assert.doesNotMatch(component, /exportar|descargar|\.csv|\.pdf/i, 'el panel no expone exportaciones de estas métricas');
assert.doesNotMatch(component, /MVP|rating|nota automática|posesión|xG|xA/i, 'no inventa valoraciones ni métricas sin fuente');
assert.match(app, /<DelegatedStatsDashboard/, 'Registro Delegado monta el nuevo dashboard');
assert.match(app, /delegatedInactiveStatEventTypes = new Set\(\['regate', 'recuperacion'\]\)[\s\S]*delegatedActiveStatEventCatalog/, 'el registro excluye regate y recuperación de su catálogo activo');
assert.match(app, /delegatedActiveStatEventCatalog\.filter[\s\S]*histórico/, 'los selectores ya no ofrecen acciones nuevas y conservan la lectura histórica');
assert.match(app, /matchesWithDelegatedEvents = matches\.filter[\s\S]*visibleMatches = matchesWithDelegatedEvents[\s\S]*<DelegatedStatsDashboard[\s\S]*matches=\{visibleMatches\}/, 'el dashboard recibe los partidos con quickEvents cargados desde el estado principal');
assert.doesNotMatch(app, /renderDelegatedRegistrySectionLegacy/, 'no conserva dos implementaciones del panel');

console.log('delegated stats UI audit: ok');
