import assert from 'node:assert/strict';
import fs from 'node:fs';

const sql = fs.readFileSync(new URL('../supabase_training_tasks.sql', import.meta.url), 'utf8');
const verify = fs.readFileSync(new URL('../supabase_training_tasks_verify.sql', import.meta.url), 'utf8');
const selectAuthorPatch = fs.readFileSync(new URL('../supabase_training_tasks_patch_select_author.sql', import.meta.url), 'utf8');
const selectAuthorPostcheck = fs.readFileSync(new URL('../supabase_training_tasks_patch_select_author_postcheck.sql', import.meta.url), 'utf8');
const taskCodePatch = fs.readFileSync(new URL('../supabase_training_tasks_patch_task_code.sql', import.meta.url), 'utf8');
const taskCodePostcheck = fs.readFileSync(new URL('../supabase_training_tasks_patch_task_code_postcheck.sql', import.meta.url), 'utf8');
const store = fs.readFileSync(new URL('../src/utils/trainingTaskStore.js', import.meta.url), 'utf8');
const trainingTasksSection = fs.readFileSync(new URL('../src/components/training/TrainingTasksSection.jsx', import.meta.url), 'utf8');

assert.match(sql, /begin;[\s\S]*to_regclass\('public\.training_tasks'\)[\s\S]*raise exception 'Tareas V1: contrato previo detectado/i);
assert.match(sql, /create table public\.training_tasks/i);
assert.match(sql, /create table public\.training_task_shares/i);
assert.match(sql, /author_user_id uuid not null references auth\.users/i);
assert.match(sql, /new\.club_id is distinct from old\.club_id/i);
assert.match(sql, /new\.author_user_id is distinct from old\.author_user_id/i);
assert.match(sql, /new\.attachment_path[\s\S]*training_task_path_matches/i);
assert.match(sql, /new\.preview_path[\s\S]*training_task_path_matches/i);
assert.match(sql, /training_task_authorized\(p_task_id uuid, p_action text\)[\s\S]*security definer set search_path = pg_catalog/i);
assert.match(sql, /public\.can_edit_club_data\(task\.club_id\)/i);
assert.match(sql, /recipient\.is_active[\s\S]*recipient\.role in \('owner','admin','staff'\)/i);
assert.match(sql, /shared_by_user_id = auth\.uid\(\)/i);
assert.match(sql, /recipient\.user_id <> auth\.uid\(\)/i);
assert.match(sql, /constraint training_tasks_phase_moment check/i);
assert.match(sql, /octet_length\(editor_payload::text\) <= 262144/i);
assert.match(sql, /training_task_storage_allowed\(p_path text, p_action text\)[\s\S]*security definer set search_path = pg_catalog/i);
assert.match(sql, /task\.preview_path = p_path or task\.attachment_path = p_path/i);
assert.match(sql, /training_task_files_select[\s\S]*training_task_storage_allowed\(name, 'read'\)/i);
assert.match(sql, /training_task_files_delete[\s\S]*training_task_storage_allowed\(name, 'write'\)/i);
assert.match(sql, /revoke all on table public\.training_tasks, public\.training_task_shares from public, anon, authenticated/i);
assert.match(sql, /grant select, insert, delete on table public\.training_task_shares to authenticated/i);
assert.match(sql, /grant select, insert, update, delete on table public\.training_tasks, public\.training_task_shares to service_role/i);
assert.match(sql, /values \('training-task-files', 'training-task-files', false, 10485760/i);
assert.doesNotMatch(sql, /drop table|drop policy|create table if not exists/i);

assert.match(verify, /^begin;/im);
assert.match(verify, /^rollback;/im);
assert.match(verify, /set local role authenticated/i);
assert.match(verify, /create or replace function pg_temp\.denied/i);
assert.match(verify, /insert into storage\.objects/i);
assert.match(verify, /NO prueba upload\/download\/remove HTTP/i);
assert.match(verify, /with inserted_task as\s*\(\s*insert into public\.training_tasks[\s\S]*returning id, task_code\s*\)/i);
assert.match(verify, /task_code[\s\S]*returning id, task_code[\s\S]*task_code = 'Vigón'/i);
assert.match(selectAuthorPatch, /alter policy training_tasks_select on public\.training_tasks[\s\S]*author_user_id\s*=\s*auth\.uid\(\)[\s\S]*can_edit_club_data\(club_id\)[\s\S]*training_task_authorized\(id,\s*'read'\)/i);
assert.doesNotMatch(selectAuthorPatch, /create table|alter table|insert into|update public\.|delete from/i);
assert.match(selectAuthorPostcheck, /set transaction read only/i);
assert.match(selectAuthorPostcheck, /training_tasks_select/i);
assert.match(selectAuthorPostcheck, /author_user_id\s*=\s*auth\.uid\(\)/i);
assert.match(taskCodePatch, /alter table public\.training_tasks\s*add column if not exists task_code text/i);
assert.match(taskCodePatch, /training_tasks_task_code_format[\s\S]*btrim\(task_code\)[\s\S]*char_length\(task_code\) between 1 and 40/i);
assert.doesNotMatch(taskCodePatch, /create policy|alter policy|drop policy|enable row level security|storage\.objects/i);
assert.match(taskCodePostcheck, /set transaction read only/i);
assert.match(taskCodePostcheck, /column_exists[\s\S]*type_is_text[\s\S]*is_nullable[\s\S]*has_no_default[\s\S]*has_no_unique_index[\s\S]*format_constraint_present/i);
assert.match(store, /from\('training_tasks'\)\.insert\(payload\)\.select\('\*'\)\.single\(\)/i);
assert.doesNotMatch(store, /TRAINING_TASK_RLS_DEBUG|insert-without-representation|safeDiagnostic|current_membership|can_edit_club_data/i);
assert.match(trainingTasksSection, /canManage\s*\?\s*<>[\s\S]*onDelete\(task\)[\s\S]*>Eliminar<\/button>/i);
assert.match(trainingTasksSection, /canManage=\{task\.author_user_id\s*===\s*userId\}/i);
assert.match(trainingTasksSection, /task\.author_user_id\s*!==\s*userId\s*\|\|\s*!window\.confirm\('¿Eliminar esta tarea\? Esta acción no se puede deshacer\.'/i);
assert.match(trainingTasksSection, /label="Código tarea"[\s\S]*placeholder="Ej\. Vigón"/i);
assert.match(trainingTasksSection, /placeholder="Nº jugadores"[\s\S]*placeholder="Objetivo"[\s\S]*Limpiar filtros/i);
assert.match(trainingTasksSection, /borderTopColor:\s*type\.color[\s\S]*Código:\s*\{task\.taskCode\}/i);
console.log('training tasks static SQL audit passed (not PostgreSQL execution)');
