import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';
import {
  TRAINING_TASK_MOMENTS,
  TRAINING_TASK_PHASES,
  TRAINING_TASK_TYPES,
  createTrainingTaskDraft,
  filterTrainingTasks,
  formatTrainingTaskPlayers,
  formatTrainingTaskSpace,
  getTrainingTaskMomentLabel,
  trainingTaskToDraft,
  validateTrainingTaskDraft,
} from '../../utils/trainingTasks';
import { duplicateTrainingTask, loadTrainingTasks, shareTrainingTask } from '../../utils/trainingTaskStore';
import { deleteTrainingTaskWithFiles, saveTrainingTaskWithFile, TRAINING_TASK_BUCKET } from '../../utils/trainingTaskFiles';

const BUCKET = TRAINING_TASK_BUCKET;
const formatDate = (value) => value ? new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium' }).format(new Date(value)) : '—';
const formatFileSize = (value) => value ? `${Math.max(1, Math.round(Number(value) / 1024))} KB` : '';

function Field({ label, children, hint }) {
  return <label className="grid min-w-0 gap-1.5"><span className="text-[10px] font-black uppercase tracking-[0.14em] text-slate-500">{label}</span>{children}{hint ? <span className="text-[10px] text-slate-600">{hint}</span> : null}</label>;
}

function TaskForm({ draft, setDraft, onCancel, onSave, saving, error, isEditing }) {
  const moments = TRAINING_TASK_MOMENTS[draft.gamePhase] || [];
  const inputClass = 'min-h-10 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm font-semibold text-white outline-none placeholder:text-slate-600 focus:border-caudal-electric/60';
  return <section className="rounded-[1.35rem] border border-white/10 bg-[#071327]/95 p-4 shadow-[0_18px_50px_rgba(0,0,0,0.22)]" aria-labelledby="training-task-form-title">
    <div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.2em] text-caudal-electric">{isEditing ? 'Editar tarea' : 'Nueva tarea'}</p><h2 id="training-task-form-title" className="mt-1 text-xl font-black text-white">Ficha de entrenamiento</h2></div><button type="button" onClick={onCancel} className="rounded-xl bg-white/[0.06] px-3 py-2 text-xs font-black text-slate-300">Cerrar</button></div>
    {error ? <p role="alert" className="mt-3 rounded-xl border border-red-200/20 bg-red-400/10 px-3 py-2 text-xs font-bold text-red-100">{error}</p> : null}
    <div className="mt-4 grid gap-3 md:grid-cols-2">
      <Field label="Nombre *"><input className={inputClass} value={draft.name} onChange={(event) => setDraft((current) => ({ ...current, name: event.target.value }))} placeholder="Ej. Rondo de tercer hombre" /></Field>
      <Field label="Tipo"><select className={inputClass} value={draft.taskType} onChange={(event) => setDraft((current) => ({ ...current, taskType: event.target.value }))}>{TRAINING_TASK_TYPES.map((value) => <option key={value}>{value}</option>)}</select></Field>
      <Field label="Objetivo principal *"><textarea className={`${inputClass} min-h-20`} value={draft.objective} onChange={(event) => setDraft((current) => ({ ...current, objective: event.target.value }))} placeholder="Qué queremos entrenar" /></Field>
      <Field label="Descripción"><textarea className={`${inputClass} min-h-20`} value={draft.description} onChange={(event) => setDraft((current) => ({ ...current, description: event.target.value }))} placeholder="Organización y consignas" /></Field>
      <Field label="Jugadores" hint="Admite formatos como 4v4+3"><input className={inputClass} value={draft.playersSpec} onChange={(event) => setDraft((current) => ({ ...current, playersSpec: event.target.value }))} placeholder="8v8+2" /></Field>
      <div className="grid grid-cols-3 gap-2"><Field label="Mín."><input type="number" min="0" className={inputClass} value={draft.playersMin} onChange={(event) => setDraft((current) => ({ ...current, playersMin: event.target.value }))} /></Field><Field label="Máx."><input type="number" min="0" className={inputClass} value={draft.playersMax} onChange={(event) => setDraft((current) => ({ ...current, playersMax: event.target.value }))} /></Field><Field label="Minutos"><input type="number" min="1" className={inputClass} value={draft.durationMinutes} onChange={(event) => setDraft((current) => ({ ...current, durationMinutes: event.target.value }))} /></Field></div>
      <div className="grid grid-cols-2 gap-2"><Field label="Ancho (m)"><input type="number" min="0" step="0.1" className={inputClass} value={draft.spaceWidthM} onChange={(event) => setDraft((current) => ({ ...current, spaceWidthM: event.target.value }))} /></Field><Field label="Largo (m)"><input type="number" min="0" step="0.1" className={inputClass} value={draft.spaceLengthM} onChange={(event) => setDraft((current) => ({ ...current, spaceLengthM: event.target.value }))} /></Field></div>
      <Field label="Material"><input className={inputClass} value={draft.material} onChange={(event) => setDraft((current) => ({ ...current, material: event.target.value }))} placeholder="Conos, petos..." /></Field>
      <Field label="Fase del juego"><select className={inputClass} value={draft.gamePhase} onChange={(event) => setDraft((current) => ({ ...current, gamePhase: event.target.value, gameMoment: '' }))}>{TRAINING_TASK_PHASES.map((phase) => <option key={phase.value} value={phase.value}>{phase.label}</option>)}</select></Field>
      {moments.length ? <Field label="Momento / subfase"><select className={inputClass} value={draft.gameMoment} onChange={(event) => setDraft((current) => ({ ...current, gameMoment: event.target.value }))}><option value="">Sin momento</option>{moments.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field> : null}
      <Field label="Contenido técnico"><textarea className={`${inputClass} min-h-20`} value={draft.technicalContent} onChange={(event) => setDraft((current) => ({ ...current, technicalContent: event.target.value }))} /></Field>
      <Field label="Contenido táctico"><textarea className={`${inputClass} min-h-20`} value={draft.tacticalContent} onChange={(event) => setDraft((current) => ({ ...current, tacticalContent: event.target.value }))} /></Field>
      <Field label="Observaciones"><textarea className={`${inputClass} min-h-16`} value={draft.observations} onChange={(event) => setDraft((current) => ({ ...current, observations: event.target.value }))} /></Field>
      <Field label="Archivo / imagen" hint="JPG, PNG, WEBP o PDF · máximo 10 MB"><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="min-h-10 w-full rounded-xl border border-dashed border-white/15 bg-black/20 px-3 py-2 text-xs text-slate-300 file:mr-2 file:rounded-lg file:border-0 file:bg-caudal-electric file:px-2 file:py-1 file:text-[10px] file:font-black" onChange={(event) => setDraft((current) => ({ ...current, file: event.target.files?.[0] || null }))} />{draft.attachmentName ? <span className="text-[10px] text-slate-500">Actual: {draft.attachmentName} {draft.attachmentSize ? `· ${formatFileSize(draft.attachmentSize)}` : ''}</span> : null}</Field>
    </div>
    <div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={onCancel} className="rounded-xl bg-white/[0.06] px-4 py-2.5 text-xs font-black text-slate-300">Cancelar</button><button type="button" onClick={onSave} disabled={saving} className="rounded-xl bg-caudal-electric px-4 py-2.5 text-xs font-black text-slate-950 disabled:opacity-50">{saving ? 'Guardando…' : isEditing ? 'Guardar cambios' : 'Crear tarea'}</button></div>
  </section>;
}

function TaskCard({ task, canManage, onOpen, onEdit, onDuplicate, onDelete, onShare, onDownload }) {
  return <article className="group overflow-hidden rounded-[1.25rem] border border-white/10 bg-[#091428]/88 shadow-[0_12px_34px_rgba(0,0,0,0.16)] transition hover:border-caudal-electric/30 hover:bg-[#0d192c]">
    <button type="button" onClick={() => onOpen(task)} className="block w-full text-left"><div className="flex h-32 items-center justify-center bg-[linear-gradient(135deg,rgba(61,217,255,0.13),rgba(255,255,255,0.035),rgba(212,0,0,0.10))] text-4xl font-black text-caudal-electric">{task.previewUrl ? <img src={task.previewUrl} alt="" className="h-full w-full object-cover" /> : 'TA'}</div><div className="p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="truncate text-base font-black text-white">{task.name}</h3><p className="mt-1 text-[10px] font-black uppercase tracking-[0.12em] text-caudal-electric">{task.taskType || 'Otro'}</p></div>{task.isShared ? <span className="shrink-0 rounded-lg border border-emerald-200/20 bg-emerald-200/10 px-2 py-1 text-[9px] font-black uppercase text-emerald-100">Compartida</span> : null}</div><div className="mt-3 flex flex-wrap gap-1.5 text-[10px] font-black uppercase tracking-[0.08em] text-slate-300">{formatTrainingTaskPlayers(task) !== 'Sin número específico' ? <span className="rounded-lg bg-white/[0.06] px-2 py-1">{formatTrainingTaskPlayers(task)}</span> : null}{task.durationMinutes ? <span className="rounded-lg bg-white/[0.06] px-2 py-1">{task.durationMinutes} min</span> : null}{formatTrainingTaskSpace(task) ? <span className="rounded-lg bg-white/[0.06] px-2 py-1">{formatTrainingTaskSpace(task)}</span> : null}</div><p className="mt-3 line-clamp-2 text-xs leading-5 text-slate-400">{task.description || task.objective}</p></div></button>
    <div className="flex flex-wrap gap-1 border-t border-white/10 px-3 py-2"><button type="button" onClick={() => onOpen(task)} className="rounded-lg px-2 py-1 text-[10px] font-black text-white hover:bg-white/10">Ver</button><button type="button" onClick={() => onDuplicate(task)} className="rounded-lg px-2 py-1 text-[10px] font-black text-slate-300 hover:bg-white/10">Duplicar</button>{task.attachmentPath ? <button type="button" onClick={() => onDownload(task)} className="rounded-lg px-2 py-1 text-[10px] font-black text-caudal-electric hover:bg-white/10">Descargar</button> : null}{canManage ? <><button type="button" onClick={() => onEdit(task)} className="ml-auto rounded-lg px-2 py-1 text-[10px] font-black text-slate-300 hover:bg-white/10">Editar</button><button type="button" onClick={() => onShare(task)} className="rounded-lg px-2 py-1 text-[10px] font-black text-slate-300 hover:bg-white/10">Compartir</button><button type="button" onClick={() => onDelete(task)} className="rounded-lg px-2 py-1 text-[10px] font-black text-red-200 hover:bg-red-500/10">Eliminar</button></> : null}</div>
  </article>;
}

export default function TrainingTasksSection({ membership = null, userId = '' }) {
  const clubId = membership?.club_id || '';
  const [tasks, setTasks] = useState([]);
  const [memberships, setMemberships] = useState([]);
  const [selected, setSelected] = useState(null);
  const [draft, setDraft] = useState(null);
  const [filters, setFilters] = useState({ search: '', taskType: '', gamePhase: '', scope: '', duration: '' });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [status, setStatus] = useState('');
  const [shareTask, setShareTask] = useState(null);
  const [shareIds, setShareIds] = useState([]);

  const refresh = async () => { if (!clubId) return; setLoading(true); setError(''); try { const [loaded, members] = await Promise.all([loadTrainingTasks(supabase, clubId), supabase.from('club_memberships').select('id,user_id,role,is_active').eq('club_id', clubId).eq('is_active', true).in('role', ['owner', 'admin', 'staff'])]); if (members.error) throw members.error; setTasks(loaded); setMemberships(members.data || []); } catch (loadError) { setError(loadError.message || 'No se pudieron cargar las tareas.'); } finally { setLoading(false); } };
  useEffect(() => { refresh(); }, [clubId]);

  const visibleTasks = useMemo(() => filterTrainingTasks(tasks, filters, userId), [tasks, filters, userId]);
  const openNew = () => { setSelected(null); setDraft(createTrainingTaskDraft()); setError(''); };
  const openEdit = (task) => { if (task.author_user_id !== userId) return; setSelected(task); setDraft(trainingTaskToDraft(task)); setError(''); };
  const save = async () => {
    const validation = validateTrainingTaskDraft(draft || {});
    if (Object.keys(validation).length) { setError(Object.values(validation)[0]); return; }
    setSaving(true);
    setError('');
    try {
      const { task: saved, cleanupPending, cleanupError } = await saveTrainingTaskWithFile(
        supabase, draft, { clubId, authorUserId: userId }, selected
      );
      setTasks((current) => selected
        ? current.map((task) => task.id === saved.id ? { ...task, ...saved, previewUrl: '' } : task)
        : [saved, ...current]);
      setDraft(null);
      setSelected(null);
      setStatus(cleanupPending.length
        ? `Tarea guardada. Limpieza pendiente de ${cleanupPending.join(', ')}: ${cleanupError?.message || 'error desconocido'}.`
        : selected ? 'Tarea actualizada.' : 'Tarea creada.');
    } catch (saveError) {
      setError(saveError.message || 'No se pudo guardar la tarea.');
    } finally { setSaving(false); }
  };
  const openTask = async (task) => { setSelected(task); if (task.previewPath && !task.previewUrl) { const { data } = await supabase.storage.from(BUCKET).createSignedUrl(task.previewPath, 3600); setTasks((current) => current.map((item) => item.id === task.id ? { ...item, previewUrl: data?.signedUrl || '' } : item)); setSelected((current) => current?.id === task.id ? { ...current, previewUrl: data?.signedUrl || '' } : current); } };
  const download = async (task) => { const { data, error: urlError } = await supabase.storage.from(BUCKET).createSignedUrl(task.attachmentPath || task.previewPath, 3600, { download: task.attachmentName || true }); if (urlError) { setError(urlError.message); return; } window.open(data.signedUrl, '_blank', 'noopener,noreferrer'); };
  const duplicate = async (task) => { try { const copy = await duplicateTrainingTask(supabase, task, { clubId, authorUserId: userId }); setTasks((current) => [copy, ...current]); setStatus('Tarea duplicada en tu biblioteca.'); } catch (duplicateError) { setError(duplicateError.message || 'No se pudo duplicar.'); } };
  const remove = async (task) => { if (task.author_user_id !== userId || !window.confirm('¿Eliminar esta tarea? Esta acción no se puede deshacer.')) return; try { await deleteTrainingTaskWithFiles(supabase, task); setTasks((current) => current.filter((item) => item.id !== task.id)); if (selected?.id === task.id) setSelected(null); setStatus('Tarea eliminada.'); } catch (deleteError) { setError(deleteError.message || 'No se pudo eliminar la tarea.'); } };
  const startShare = async (task) => { if (task.author_user_id !== userId) return; const { data, error: shareError } = await supabase.from('training_task_shares').select('membership_id').eq('task_id', task.id); if (shareError) { setError(shareError.message); return; } setShareTask(task); setShareIds((data || []).map((row) => row.membership_id)); };
  const saveShare = async () => { try { await shareTrainingTask(supabase, shareTask.id, shareIds, userId); setShareTask(null); await refresh(); setStatus('Compartición actualizada.'); } catch (shareError) { setError(shareError.message || 'No se pudo compartir.'); } };

  if (!clubId) return <section className="rounded-2xl border border-amber-200/20 bg-amber-200/10 p-5 text-sm text-amber-100">No hay un club activo disponible para cargar Tareas.</section>;
  return <main className="space-y-5">
    <header className="rounded-[1.35rem] border border-white/10 bg-white/[0.04] p-4 shadow-[0_16px_48px_rgba(0,0,0,0.16)] sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[0.22em] text-caudal-electric">Biblioteca operativa</p><h1 className="mt-1 text-2xl font-black text-white">Tareas</h1><p className="mt-1 text-sm text-slate-400">Biblioteca de tareas de entrenamiento para el cuerpo técnico.</p></div><button type="button" onClick={openNew} className="rounded-xl bg-caudal-electric px-4 py-2.5 text-xs font-black text-slate-950">+ Nueva tarea</button></div>{status ? <p className="mt-3 rounded-xl bg-emerald-400/10 px-3 py-2 text-xs font-bold text-emerald-100">{status}</p> : null}{error && !draft ? <p role="alert" className="mt-3 rounded-xl bg-red-400/10 px-3 py-2 text-xs font-bold text-red-100">{error}</p> : null}</header>
    {draft ? <TaskForm draft={draft} setDraft={setDraft} onCancel={() => setDraft(null)} onSave={save} saving={saving} error={error} isEditing={Boolean(selected?.id)} /> : null}
    <section className="rounded-[1.25rem] border border-white/10 bg-[#091428]/78 p-3 sm:p-4"><div className="grid gap-2 md:grid-cols-[minmax(220px,1fr)_repeat(4,minmax(120px,0.45fr))]"><input value={filters.search} onChange={(event) => setFilters((current) => ({ ...current, search: event.target.value }))} placeholder="Buscar nombre, descripción u objetivo..." className="min-h-10 rounded-xl border border-white/10 bg-black/20 px-3 text-sm font-semibold text-white outline-none placeholder:text-slate-600 focus:border-caudal-electric/60" /><select value={filters.taskType} onChange={(event) => setFilters((current) => ({ ...current, taskType: event.target.value }))} className="min-h-10 rounded-xl border border-white/10 bg-white px-2 text-xs font-bold text-slate-950"><option value="">Todos los tipos</option>{TRAINING_TASK_TYPES.map((type) => <option key={type}>{type}</option>)}</select><select value={filters.gamePhase} onChange={(event) => setFilters((current) => ({ ...current, gamePhase: event.target.value }))} className="min-h-10 rounded-xl border border-white/10 bg-white px-2 text-xs font-bold text-slate-950"><option value="">Todas las fases</option>{TRAINING_TASK_PHASES.slice(1).map((phase) => <option key={phase.value} value={phase.value}>{phase.label}</option>)}</select><select value={filters.duration} onChange={(event) => setFilters((current) => ({ ...current, duration: event.target.value }))} className="min-h-10 rounded-xl border border-white/10 bg-white px-2 text-xs font-bold text-slate-950"><option value="">Cualquier duración</option><option value="short">Hasta 15 min</option><option value="medium">16–30 min</option><option value="long">Más de 30 min</option></select><select value={filters.scope} onChange={(event) => setFilters((current) => ({ ...current, scope: event.target.value }))} className="min-h-10 rounded-xl border border-white/10 bg-white px-2 text-xs font-bold text-slate-950"><option value="">Todas</option><option value="mine">Mías</option><option value="shared">Compartidas</option></select></div></section>
    {loading ? <div className="rounded-2xl border border-dashed border-white/10 p-8 text-center text-sm text-slate-500">Cargando tareas…</div> : error && !tasks.length ? <div role="alert" className="rounded-2xl border border-red-300/20 bg-red-400/10 p-8 text-center text-sm text-red-100">No se pudieron cargar las tareas.</div> : visibleTasks.length ? <div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-3">{visibleTasks.map((task) => <TaskCard key={task.id} task={task} canManage={task.author_user_id === userId} onOpen={openTask} onEdit={openEdit} onDuplicate={duplicate} onDelete={remove} onShare={startShare} onDownload={download} />)}</div> : <div className="rounded-2xl border border-dashed border-white/10 bg-white/[0.025] p-8 text-center"><p className="text-sm font-black text-white">No hay tareas todavía</p><p className="mt-1 text-xs text-slate-500">Crea la primera tarea de entrenamiento para tu biblioteca.</p><button type="button" onClick={openNew} className="mt-4 rounded-xl bg-caudal-electric px-4 py-2 text-xs font-black text-slate-950">+ Nueva tarea</button></div>}
    {selected && !draft ? <section className="rounded-[1.35rem] border border-caudal-electric/20 bg-[#071327]/95 p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-caudal-electric">Detalle de tarea</p><h2 className="mt-1 text-xl font-black text-white">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">Creada {formatDate(selected.created_at)} · actualizada {formatDate(selected.updated_at)}</p></div><button type="button" onClick={() => setSelected(null)} className="rounded-xl bg-white/[0.06] px-3 py-2 text-xs font-black text-slate-300">Cerrar</button></div><div className="mt-4 grid gap-4 lg:grid-cols-[240px_1fr]"><div className="flex min-h-40 items-center justify-center overflow-hidden rounded-2xl bg-white/[0.04] text-4xl font-black text-caudal-electric">{selected.previewUrl ? <img src={selected.previewUrl} alt="" className="h-full max-h-64 w-full object-contain" /> : 'TA'}</div><div className="grid gap-3 text-sm text-slate-300 sm:grid-cols-2"><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Objetivo</p><p className="mt-1">{selected.objective}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Organización</p><p className="mt-1">{selected.taskType} · {formatTrainingTaskPlayers(selected)}{selected.durationMinutes ? ` · ${selected.durationMinutes} min` : ''}{formatTrainingTaskSpace(selected) ? ` · ${formatTrainingTaskSpace(selected)}` : ''}</p></div><div className="sm:col-span-2"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Descripción</p><p className="mt-1 whitespace-pre-wrap">{selected.description || 'Sin descripción.'}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Técnico</p><p className="mt-1 whitespace-pre-wrap">{selected.technicalContent || '—'}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Táctico / fase</p><p className="mt-1 whitespace-pre-wrap">{selected.tacticalContent || '—'}{selected.gameMoment ? ` · ${getTrainingTaskMomentLabel(selected.gamePhase, selected.gameMoment) || selected.gameMoment}` : ''}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Material</p><p className="mt-1">{selected.material || '—'}</p></div><div><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">Adjunto</p>{selected.attachmentPath ? <button type="button" onClick={() => download(selected)} className="mt-1 text-left text-caudal-electric underline">{selected.attachmentName || 'Descargar archivo'}</button> : <p className="mt-1">Sin archivo.</p>}</div></div></div></section> : null}
    {shareTask ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><section className="w-full max-w-lg rounded-2xl border border-white/10 bg-[#071327] p-5 shadow-2xl"><h2 className="text-lg font-black text-white">Compartir tarea</h2><p className="mt-1 text-xs text-slate-500">Selecciona miembros STAFF del mismo club. No se comparte con jugadores.</p><div className="mt-4 grid max-h-64 gap-2 overflow-y-auto">{memberships.filter((member) => member.user_id !== userId).map((member) => <label key={member.id} className="flex items-center gap-3 rounded-xl bg-white/[0.04] px-3 py-2 text-xs text-slate-300"><input type="checkbox" checked={shareIds.includes(member.id)} onChange={(event) => setShareIds((current) => event.target.checked ? [...current, member.id] : current.filter((id) => id !== member.id))} />{member.role.toUpperCase()} · {member.user_id}</label>)}</div><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setShareTask(null)} className="rounded-xl bg-white/[0.06] px-3 py-2 text-xs font-black text-slate-300">Cancelar</button><button type="button" onClick={saveShare} className="rounded-xl bg-caudal-electric px-3 py-2 text-xs font-black text-slate-950">Guardar compartición</button></div></section></div> : null}
  </main>;
}
